- name: Assurez-vous que Helm est install\u00e9 sur la VM
  shell: |
    which helm || snap install helm --classic
  args:
    executable: /bin/bash

- name: Assurez-vous que kubectl pointe vers microk8s
  shell: |
    microk8s status --wait-ready
    microk8s enable dns storage
    microk8s kubectl get nodes
  environment:
    KUBECONFIG: ""

- name: Cr\u00e9ez le namespace s\u2019il n\u2019existe pas
  shell: microk8s kubectl create namespace {{ chart_namespace }} || true

- name: Copie du chart Helm vers la VM
  copy:
    src: files/helm_chart/{{ chart_name }}
    dest: /tmp/helm_chart/
    mode: 0755

- name: D\u00e9ployer le chart Helm via microk8s
  shell: >
    microk8s helm3 upgrade --install {{ chart_name }}
    {{ chart_path }}
    --namespace {{ chart_namespace }}
    --create-namespace
  args:
    chdir: /tmp/helm_chart/
