FROM node:18-alpine

# Définit le répertoire de travail
WORKDIR /usr/src/app

# Copie uniquement les fichiers package.json et package-lock.json
COPY ./frontend/package*.json ./

# Installation des dépendances
RUN npm install

# Copie uniquement le code source du frontend
COPY ./frontend ./

# Expose le port utilisé par le serveur de développement React (par défaut 3000)
EXPOSE 3000

# Commande d’exécution pour lancer le serveur React en mode dev
CMD ["npm", "start"]