{
    "name": "bibind_elearning",
    "version": "1.0.0",
    "author": "Audrey-Roch Houssou",
    "company": "Bibind",
    "website": "http://www.bibind.com",
    "depends": ["website_slides", "product"],
    "category": "Elearning",
    "description": "Module d'intégration des formations Bibind dans Odoo eLearning.",
    "license": "LGPL-3",
    "data": [
        "security/ir.model.access.csv",
        "security/elearning_security.xml",
        "views/elearning_views.xml",
        "data/formation_agil_scrum.xml",
        "data/formation_arhitecture_urbanisation.xml",
        "data/formation_big_data_machine_earning.xml",
        "data/formation_devops.xml",
        "data/formation_drupal10_chefprojet.xml",
        "data/formation_drupal10_developpeur.xml",
        "data/formation_magent2_developpeur.xml",
        "data/formation_magento2_apiamazone.xml",
        "data/formation_magento2_chefprojet.xml",
        "data/formation_odoo_developpeur.xml",
        "data/formation_odoo_gerant_chefprojet.xml",
        "data/Formation_openstack.xml",
        "data/formation_POO.xml",
        "data/formation_terraform.xml",
        "data/formation_sécurite_kalilinux.xml"
    ],
    "installable": True,
    "application": True,
}
