{
    'name': 'Bibind Portal Projects',
    'version': '0.1.0',
    'summary': 'Project management and GitLab integration for Bibind portal',
    'depends': ['bibind_portal', 'project', 'mail'],
    'data': [
        'security/ir.model.access.csv',
        'security/rules.xml',
        'data/res_groups.xml',
        'data/mail_templates.xml',
        'data/cron.xml',
        'views/portal_menu.xml',
        'views/project_views.xml',
        'views/backlog_views.xml',
        'views/sprint_views.xml',
        'views/budget_views.xml',
        'views/billing_views.xml',
        'views/docs_views.xml',
        'views/sync_views.xml',
        'views/project_wizard_views.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'partenaires/bibind_portal_projects/static/src/js/burn_chart.js',
            'partenaires/bibind_portal_projects/static/src/xml/burn_chart.xml',
        ],
    },
    'demo': ['data/demo.xml'],
    'installable': True,
    'application': False,
}
